---
title: "class05"
author: "Nate Tran"
format: pdf
---
#install.packages("ggplot2")
#install.packages("gapminder")

```{r}
head(cars, 10)
```

```{r}
plot(cars)
```

ggplot requires 3 components:

**1. Data** (in the form of a data.frame)\
**2. Aesthetics** (aes() for short)\
**3. Geometries** (e.g. geom_point() or geom_line())

```{r}
library(ggplot2)
ggplot(cars) + 
  aes(x=speed, y=dist) + 
  geom_point() + 
  geom_smooth(method = "lm", se = F) +
  labs(title = "Speed vs. Distance") +
  xlab("mph") +
  ylab("miles")
```

## Gene Expression

```{r}
genes <- read.delim("https://bioboot.github.io/bimm143_S20/class-material/up_down_expression.txt")
head(genes)
nrow(genes)
colnames(genes)
ncol(genes)
table(genes$State)
round((table(genes$State)/nrow(genes))*100, 2)
```

There are `r nrow(genes)` genes in this dataset.

```{r}
ggplot(genes) +
  aes(x=Condition1, y=Condition2, color = State) +
  geom_point() + 
  scale_color_manual(values = c("blue", "gray", "red")) +
  labs(title = "Gene Expression Changes upon Drug Treatment") +
  xlab("Control (no drug)") +
  ylab("Drug Treatment")
```

## Gapminder

```{r}
library(gapminder)
length(unique(gapminder$country))
gapminder[which.min(gapminder$pop), "country"]
gapminder[which.min(gapminder$pop),]
```

```{r}
ggplot(gapminder) +
  aes(x=gdpPercap, y=lifeExp, color=continent, size=pop) +
  geom_point(alpha=0.4) +
  facet_wrap("continent")
```
